global:
    scrape_interval: 15s
    evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    scrape_timeout: 15s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'vet'
    scrape_interval: 15s
    scrape_timeout: 15s
    static_configs:
      - targets: ['vet:3000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: [ 'node-exporter:9100' ]

rule_files:
  - './alert_rules'